name: Foundry

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  forge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1

      - name: Run Forge tests
        run: forge test -vvv
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          FOUNDRY_FUZZ_RUNS: 64
